#!/system/bin/sh

grep -oE 'init_[0-9_]+' /vendor/etc/selinux/nonplat_sepolicy.cil | \
	uniq | \
	sort -n | \
	head -n 1 | \
	sed -E 's/.*init_([0-9]+).*/\1/g' | \
while read version;do
	setprop persist.sys.vndk $version
done

if [ -d /sys/module/five ];then
	mount -o bind /system/phh/empty /sbin/adbd
	setprop sys.phh.five true
else
	mount -o bind /system/bin/adbd /sbin/adbd
fi

   setprop persist.sys.radio.ussd.fix true

